pcl_to_scan:
  ros__parameters:
    target_frame: livox_frame_level
    transform_tolerance: 0.01
    min_height: -0.5
    max_height: 0.05
    angle_min: 0.0
    angle_max: 3.14
    angle_increment: 0.0872665
    range_min: 0.4
    range_max: 30.0
    use_inf: true
    inf_epsilon: 1.0
