pcl_to_scan:
  ros__parameters:
    target_frame: body_frd_level
    transform_tolerance: 0.01
    min_height: -0.30
    max_height: 0.30
    angle_increment: 0.0872665
    range_min: 0.4
    range_max: 30.0
    use_inf: true
    inf_epsilon: 1.0
